### ISSUE TITLE
exposed API key

### ISSUE THREAD

**Issue by nathanielbelen** [teamduckhunt/NotNaked#79]
When deployed, your API key will be visible in devtools. Anything stored client-side/in the browser will be easily accesible to the user. Google around and try to the best practice of hitting a private api with React (proxy?).

https://github.com/teamduckhunt/NotNaked/blob/cf218e6c6aa8d781705372c75759454940f55324/src/services/products.js#L2

**Comment by heemo521** [comment]
Created .env file and configure to work with webpack
