### ISSUE TITLE
unnecessary dependencies

### ISSUE THREAD

**Issue by nathanielbelen** [teamduckhunt/NotNaked#87]
consider moving dependencies that the end-user and production does not need to your dev dependencies

https://nodejs.dev/learn/npm-dependencies-and-devdependencies
https://github.com/teamduckhunt/NotNaked/blob/cf218e6c6aa8d781705372c75759454940f55324/package.json#L28-L30
https://github.com/teamduckhunt/NotNaked/blob/cf218e6c6aa8d781705372c75759454940f55324/package.json#L24

**Comment by heemo521** [comment]
Dependecies moved to dev dependencies
